name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  Integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: start mysql
        run: sudo /etc/init.d/mysql start
      
      - name: Create MySQL Database
        run: |
          mysql -h localhost -u root -proot -e "CREATE DATABASE csye6225;"
          mysql -h localhost -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.MYSQL_PASS }}';"
         
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: subdir/go.sum

      - name: Install dependencies
        run: go mod tidy && go mod download
        
      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: |
          go test -v ./...

